import { Platform, StyleSheet } from 'react-native';
import { color, space, component } from '@/assets';

/**
 * Auto-generated shared StyleSheet.
 *
 * Holds style objects that are identical across two or more screens so each
 * object is declared exactly once instead of being repeated per screen. Screens
 * reference these via `sharedStyles.<key>`. Generated by the shared-style
 * hoisting pass — do not edit by hand.
 */
export const sharedStyles = StyleSheet.create({
  button: {
    paddingBottom: space['2'],
    borderRadius: space['3'],
    paddingLeft: space['3'],
    alignItems: 'center',
    height: component.button.height,
    paddingTop: space['2'],
    backgroundColor: color.brand.primary,
    justifyContent: 'center',
    flexDirection: 'row',
    paddingRight: space['3'],
    ...Platform.select({ web: { display: 'flex' }, default: {} }),
  },
  container: {
    height: '100%',
    width: '100%',
    backgroundColor: color.surface.default,
    justifyContent: 'flex-start',
    alignItems: 'stretch',
  },
  buttonText: { color: color.brand.onPrimary },
  buttonIconStyles: {
    iconSize: component.icon.size.md,
    color: color.brand.onPrimary,
  },
  textDrag: { flexBasis: 'auto' },
  buttonTrailingIconStyles: { marginLeft: space['1'] },
  buttonLeadingIconStyles: { marginRight: space['1'] },
  greetingMsg: {
    overflow: 'visible',
    textAlign: 'left',
    ...Platform.select({ web: { whiteSpace: 'pre-wrap' }, default: {} }),
  },
});
