import { color } from './color';

export const text = {
  body: {
    medium: {
      color: color.text.primary,
      fontSize: 14,
      fontStyle: 'normal',
      fontFamily: 'Poppins-400-normal',
      fontWeight: 400,
      letterSpacing: 0,
    },
    small: {
      color: color.text.primary,
      fontSize: 12,
      fontStyle: 'normal',
      fontFamily: 'Poppins-400-normal',
      fontWeight: 400,
      letterSpacing: 0,
    },
    large: {
      color: color.text.primary,
      fontSize: 16,
      fontStyle: 'normal',
      fontFamily: 'Poppins-400-normal',
      fontWeight: 400,
      letterSpacing: 0,
    },
  },
  label: {
    large: {
      color: color.text.primary,
      fontSize: 16,
      fontStyle: 'normal',
      fontFamily: 'Poppins-500-normal',
      fontWeight: 500,
      letterSpacing: 0,
    },
    medium: {
      color: color.text.primary,
      fontSize: 14,
      fontStyle: 'normal',
      fontFamily: 'Poppins-500-normal',
      fontWeight: 500,
      letterSpacing: 0,
    },
    small: {
      color: color.text.primary,
      fontSize: 12,
      fontStyle: 'normal',
      fontFamily: 'Poppins-500-normal',
      fontWeight: 500,
      letterSpacing: 0,
    },
  },
  title: {
    large: {
      color: color.text.primary,
      fontSize: 24,
      fontStyle: 'normal',
      fontFamily: 'Poppins-600-normal',
      fontWeight: 600,
      letterSpacing: 0,
    },
    medium: {
      color: color.text.primary,
      fontSize: 18,
      fontStyle: 'normal',
      fontFamily: 'Poppins-600-normal',
      fontWeight: 600,
      letterSpacing: 0,
    },
    small: {
      color: color.text.primary,
      fontSize: 14,
      fontStyle: 'normal',
      fontFamily: 'Poppins-600-normal',
      fontWeight: 600,
      letterSpacing: 0,
    },
  },
  heading: {
    large: {
      color: color.text.primary,
      fontSize: 32,
      fontStyle: 'normal',
      fontFamily: 'Poppins-700-normal',
      fontWeight: 700,
      letterSpacing: -0.02,
    },
    medium: {
      color: color.text.primary,
      fontSize: 24,
      fontStyle: 'normal',
      fontFamily: 'Poppins-700-normal',
      fontWeight: 700,
      letterSpacing: -0.01,
    },
    small: {
      color: color.text.primary,
      fontSize: 18,
      fontStyle: 'normal',
      fontFamily: 'Poppins-700-normal',
      fontWeight: 700,
      letterSpacing: 0,
    },
  },
  hint: {
    color: color.text.tertiary,
    fontSize: 10,
    fontStyle: 'normal',
    fontFamily: 'Poppins-400-normal',
    fontWeight: 400,
    letterSpacing: 0,
  },
};
